# Generated by Django 2.2.24 on 2021-07-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210713_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
