# Generated by Django 2.2.24 on 2021-07-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210713_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='chosen_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.QuestionAnswer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
        ),
    ]
